WebApplication.Net/WebApplication.Net/Areas/FirstMVC/Controllers/Default1Controller.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication.Net.FirstMVC.Controllers
{
    [Area("FirstMVC")]
    public class Default1Controller : Controller
    {
        //
        // GET: /FirstMVC/Default1/Action1
        public ActionResult Action1()
        {
            HttpContext.Session.SetString("Session1", "UntilBrowserCloses");
            TempData["FortheFullRequest"] = "FortheFullRequest";
            ViewData["Myval"] = "ControllertoView";
            ViewBag.MyVal = "ControllertoView";
            return RedirectToAction("SomeOtherAction", "Default2");
        }
    }
}

WebApplication.Net/WebApplication.Net/Areas/FirstMVC/Controllers/Default2Controller.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication.Net.FirstMVC.Controllers
{
    [Area("FirstMVC")]
    public class Default2Controller : Controller
    {
        //
        // GET: /FirstMVC/Default2/SomeOtherAction
        public ActionResult SomeOtherAction()
        {
            string str = Convert.ToString(TempData["FortheFullRequest"]);
            string str2 = HttpContext.Session.GetString("Session1");
            string str3 = Convert.ToString(ViewData["Myval"]);
            string str4 = ViewBag.MyVal;
            ViewData["Myval"] = "ControllertoView";
            ViewBag.MyVal = "ControllertoViewCollection";
            return View("SomeView");
        }
    }
}

WebApplication.Net/WebApplication.Net/Areas/FirstMVC/Controllers/SomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication.Net.FirstMVC.Controllers
{
    [Area("FirstMVC")]
    public class SomeController : Controller
    {
        // GET: /FirstMVC/Some/MyView
        public ActionResult MyView()
        {
            return View();
        }
    }
}

WebApplication.Net/WebApplication.Net/Areas/FirstMVC/Views/Default2/SomeView.cshtml
@using Microsoft.AspNetCore.Http

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SomeView</title>
</head>
<body>
    <div> 
        @TempData["FortheFullRequest"]<br />
        @ViewData["Myval"]<br />
        @Context.Session.GetString("Session1")<br />
        @ViewBag.MyVal<br />
        @Html.ActionLink("Click", "Action1", "Default1")
    </div>
</body>
</html>